/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiInputTask } from './ApiInputTask';
import {
    ApiInputTaskFromJSON,
    ApiInputTaskFromJSONTyped,
    ApiInputTaskToJSON,
} from './ApiInputTask';

/**
 * 
 * @export
 * @interface AddApiTaskToDraftFeatureBody
 */
export interface AddApiTaskToDraftFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof AddApiTaskToDraftFeatureBody
     */
    featureId: string;
    /**
     * 
     * @type {ApiInputTask}
     * @memberof AddApiTaskToDraftFeatureBody
     */
    task: ApiInputTask;
}

/**
 * Check if a given object implements the AddApiTaskToDraftFeatureBody interface.
 */
export function instanceOfAddApiTaskToDraftFeatureBody(value: object): value is AddApiTaskToDraftFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('task' in value) || value['task'] === undefined) return false;
    return true;
}

export function AddApiTaskToDraftFeatureBodyFromJSON(json: any): AddApiTaskToDraftFeatureBody {
    return AddApiTaskToDraftFeatureBodyFromJSONTyped(json, false);
}

export function AddApiTaskToDraftFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddApiTaskToDraftFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'task': ApiInputTaskFromJSON(json['task']),
    };
}

export function AddApiTaskToDraftFeatureBodyToJSON(value?: AddApiTaskToDraftFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'task': ApiInputTaskToJSON(value['task']),
    };
}

