/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddDraftFeatureBody
 */
export interface AddDraftFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof AddDraftFeatureBody
     */
    containerId: string;
    /**
     * 
     * @type {string}
     * @memberof AddDraftFeatureBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddDraftFeatureBody
     */
    objective: string;
    /**
     * 
     * @type {string}
     * @memberof AddDraftFeatureBody
     */
    flowOverview: string;
}

/**
 * Check if a given object implements the AddDraftFeatureBody interface.
 */
export function instanceOfAddDraftFeatureBody(value: object): value is AddDraftFeatureBody {
    if (!('containerId' in value) || value['containerId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('objective' in value) || value['objective'] === undefined) return false;
    if (!('flowOverview' in value) || value['flowOverview'] === undefined) return false;
    return true;
}

export function AddDraftFeatureBodyFromJSON(json: any): AddDraftFeatureBody {
    return AddDraftFeatureBodyFromJSONTyped(json, false);
}

export function AddDraftFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddDraftFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'containerId': json['containerId'],
        'name': json['name'],
        'objective': json['objective'],
        'flowOverview': json['flowOverview'],
    };
}

export function AddDraftFeatureBodyToJSON(value?: AddDraftFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'containerId': value['containerId'],
        'name': value['name'],
        'objective': value['objective'],
        'flowOverview': value['flowOverview'],
    };
}

