/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BpnTransition } from './BpnTransition';
import {
    BpnTransitionFromJSON,
    BpnTransitionFromJSONTyped,
    BpnTransitionToJSON,
} from './BpnTransition';

/**
 * 
 * @export
 * @interface AddTransitionToDraftFeatureBody
 */
export interface AddTransitionToDraftFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof AddTransitionToDraftFeatureBody
     */
    featureId: string;
    /**
     * 
     * @type {BpnTransition}
     * @memberof AddTransitionToDraftFeatureBody
     */
    transition: BpnTransition;
}

/**
 * Check if a given object implements the AddTransitionToDraftFeatureBody interface.
 */
export function instanceOfAddTransitionToDraftFeatureBody(value: object): value is AddTransitionToDraftFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('transition' in value) || value['transition'] === undefined) return false;
    return true;
}

export function AddTransitionToDraftFeatureBodyFromJSON(json: any): AddTransitionToDraftFeatureBody {
    return AddTransitionToDraftFeatureBodyFromJSONTyped(json, false);
}

export function AddTransitionToDraftFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTransitionToDraftFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'transition': BpnTransitionFromJSON(json['transition']),
    };
}

export function AddTransitionToDraftFeatureBodyToJSON(value?: AddTransitionToDraftFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'transition': BpnTransitionToJSON(value['transition']),
    };
}

