/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Api
 */
export interface Api {
    /**
     * 
     * @type {string}
     * @memberof Api
     */
    name?: string;
}

/**
 * Check if a given object implements the Api interface.
 */
export function instanceOfApi(value: object): value is Api {
    return true;
}

export function ApiFromJSON(json: any): Api {
    return ApiFromJSONTyped(json, false);
}

export function ApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Api {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ApiToJSON(value?: Api | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

