/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssertOperation } from './AssertOperation';
import {
    AssertOperationFromJSON,
    AssertOperationFromJSONTyped,
    AssertOperationToJSON,
} from './AssertOperation';

/**
 * 
 * @export
 * @interface AssertDefinition
 */
export interface AssertDefinition {
    /**
     * 
     * @type {string}
     * @memberof AssertDefinition
     */
    field?: string;
    /**
     * 
     * @type {AssertOperation}
     * @memberof AssertDefinition
     */
    operation?: AssertOperation;
    /**
     * 
     * @type {string}
     * @memberof AssertDefinition
     */
    expectedValue?: string | null;
}



/**
 * Check if a given object implements the AssertDefinition interface.
 */
export function instanceOfAssertDefinition(value: object): value is AssertDefinition {
    return true;
}

export function AssertDefinitionFromJSON(json: any): AssertDefinition {
    return AssertDefinitionFromJSONTyped(json, false);
}

export function AssertDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'operation': json['operation'] == null ? undefined : AssertOperationFromJSON(json['operation']),
        'expectedValue': json['expectedValue'] == null ? undefined : json['expectedValue'],
    };
}

export function AssertDefinitionToJSON(value?: AssertDefinition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'field': value['field'],
        'operation': AssertOperationToJSON(value['operation']),
        'expectedValue': value['expectedValue'],
    };
}

