/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AssertOperation = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15
} as const;
export type AssertOperation = typeof AssertOperation[keyof typeof AssertOperation];


export function instanceOfAssertOperation(value: any): boolean {
    for (const key in AssertOperation) {
        if (Object.prototype.hasOwnProperty.call(AssertOperation, key)) {
            if (AssertOperation[key as keyof typeof AssertOperation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssertOperationFromJSON(json: any): AssertOperation {
    return AssertOperationFromJSONTyped(json, false);
}

export function AssertOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertOperation {
    return json as AssertOperation;
}

export function AssertOperationToJSON(value?: AssertOperation | null): any {
    return value as any;
}

