/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureDetails } from './FeatureDetails';
import {
    FeatureDetailsFromJSON,
    FeatureDetailsFromJSONTyped,
    FeatureDetailsToJSON,
} from './FeatureDetails';

/**
 * 
 * @export
 * @interface BpnContext
 */
export interface BpnContext {
    /**
     * 
     * @type {string}
     * @memberof BpnContext
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BpnContext
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof BpnContext
     */
    lastUpdatedTimestamp: Date;
    /**
     * 
     * @type {Date}
     * @memberof BpnContext
     */
    createdTimestamp: Date;
    /**
     * 
     * @type {Array<FeatureDetails>}
     * @memberof BpnContext
     */
    features: Array<FeatureDetails>;
}

/**
 * Check if a given object implements the BpnContext interface.
 */
export function instanceOfBpnContext(value: object): value is BpnContext {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('lastUpdatedTimestamp' in value) || value['lastUpdatedTimestamp'] === undefined) return false;
    if (!('createdTimestamp' in value) || value['createdTimestamp'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    return true;
}

export function BpnContextFromJSON(json: any): BpnContext {
    return BpnContextFromJSONTyped(json, false);
}

export function BpnContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnContext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'lastUpdatedTimestamp': (new Date(json['lastUpdatedTimestamp'])),
        'createdTimestamp': (new Date(json['createdTimestamp'])),
        'features': ((json['features'] as Array<any>).map(FeatureDetailsFromJSON)),
    };
}

export function BpnContextToJSON(value?: BpnContext | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'lastUpdatedTimestamp': ((value['lastUpdatedTimestamp']).toISOString()),
        'createdTimestamp': ((value['createdTimestamp']).toISOString()),
        'features': ((value['features'] as Array<any>).map(FeatureDetailsToJSON)),
    };
}

