/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BpnFeatureDiagram } from './BpnFeatureDiagram';
import {
    BpnFeatureDiagramFromJSON,
    BpnFeatureDiagramFromJSONTyped,
    BpnFeatureDiagramToJSON,
} from './BpnFeatureDiagram';
import type { BpnTransition } from './BpnTransition';
import {
    BpnTransitionFromJSON,
    BpnTransitionFromJSONTyped,
    BpnTransitionToJSON,
} from './BpnTransition';
import type { Environment } from './Environment';
import {
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
} from './Environment';
import type { BpnTask } from './BpnTask';
import {
    BpnTaskFromJSON,
    BpnTaskFromJSONTyped,
    BpnTaskToJSON,
} from './BpnTask';

/**
 * 
 * @export
 * @interface BpnFeatureRevision
 */
export interface BpnFeatureRevision {
    /**
     * 
     * @type {BpnFeatureDiagram}
     * @memberof BpnFeatureRevision
     */
    diagram?: BpnFeatureDiagram;
    /**
     * 
     * @type {string}
     * @memberof BpnFeatureRevision
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BpnFeatureRevision
     */
    objective?: string;
    /**
     * 
     * @type {string}
     * @memberof BpnFeatureRevision
     */
    flowOverview?: string;
    /**
     * 
     * @type {string}
     * @memberof BpnFeatureRevision
     */
    releasedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof BpnFeatureRevision
     */
    releasedDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BpnFeatureRevision
     */
    revision?: number;
    /**
     * 
     * @type {Array<BpnTask>}
     * @memberof BpnFeatureRevision
     */
    tasks?: Array<BpnTask>;
    /**
     * 
     * @type {Array<BpnTransition>}
     * @memberof BpnFeatureRevision
     */
    transitions?: Array<BpnTransition>;
    /**
     * 
     * @type {Array<Environment>}
     * @memberof BpnFeatureRevision
     */
    targetEnvironments?: Array<Environment>;
}

/**
 * Check if a given object implements the BpnFeatureRevision interface.
 */
export function instanceOfBpnFeatureRevision(value: object): value is BpnFeatureRevision {
    return true;
}

export function BpnFeatureRevisionFromJSON(json: any): BpnFeatureRevision {
    return BpnFeatureRevisionFromJSONTyped(json, false);
}

export function BpnFeatureRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnFeatureRevision {
    if (json == null) {
        return json;
    }
    return {
        
        'diagram': json['diagram'] == null ? undefined : BpnFeatureDiagramFromJSON(json['diagram']),
        'name': json['name'] == null ? undefined : json['name'],
        'objective': json['objective'] == null ? undefined : json['objective'],
        'flowOverview': json['flowOverview'] == null ? undefined : json['flowOverview'],
        'releasedBy': json['releasedBy'] == null ? undefined : json['releasedBy'],
        'releasedDate': json['releasedDate'] == null ? undefined : (new Date(json['releasedDate'])),
        'revision': json['revision'] == null ? undefined : json['revision'],
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(BpnTaskFromJSON)),
        'transitions': json['transitions'] == null ? undefined : ((json['transitions'] as Array<any>).map(BpnTransitionFromJSON)),
        'targetEnvironments': json['targetEnvironments'] == null ? undefined : ((json['targetEnvironments'] as Array<any>).map(EnvironmentFromJSON)),
    };
}

export function BpnFeatureRevisionToJSON(value?: BpnFeatureRevision | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'diagram': BpnFeatureDiagramToJSON(value['diagram']),
        'name': value['name'],
        'objective': value['objective'],
        'flowOverview': value['flowOverview'],
        'releasedBy': value['releasedBy'],
        'releasedDate': value['releasedDate'] == null ? undefined : ((value['releasedDate'] as any).toISOString()),
        'revision': value['revision'],
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(BpnTaskToJSON)),
        'transitions': value['transitions'] == null ? undefined : ((value['transitions'] as Array<any>).map(BpnTransitionToJSON)),
        'targetEnvironments': value['targetEnvironments'] == null ? undefined : ((value['targetEnvironments'] as Array<any>).map(EnvironmentToJSON)),
    };
}

