/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stats } from './Stats';
import {
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './Stats';
import type { TaskStats } from './TaskStats';
import {
    TaskStatsFromJSON,
    TaskStatsFromJSONTyped,
    TaskStatsToJSON,
} from './TaskStats';

/**
 * 
 * @export
 * @interface BpnFeatureVersionStat
 */
export interface BpnFeatureVersionStat {
    /**
     * 
     * @type {string}
     * @memberof BpnFeatureVersionStat
     */
    id: string;
    /**
     * 
     * @type {Stats}
     * @memberof BpnFeatureVersionStat
     */
    featureStats: Stats;
    /**
     * 
     * @type {Stats}
     * @memberof BpnFeatureVersionStat
     */
    versionStats: Stats;
    /**
     * 
     * @type {Array<TaskStats>}
     * @memberof BpnFeatureVersionStat
     */
    taskStats: Array<TaskStats>;
}

/**
 * Check if a given object implements the BpnFeatureVersionStat interface.
 */
export function instanceOfBpnFeatureVersionStat(value: object): value is BpnFeatureVersionStat {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('featureStats' in value) || value['featureStats'] === undefined) return false;
    if (!('versionStats' in value) || value['versionStats'] === undefined) return false;
    if (!('taskStats' in value) || value['taskStats'] === undefined) return false;
    return true;
}

export function BpnFeatureVersionStatFromJSON(json: any): BpnFeatureVersionStat {
    return BpnFeatureVersionStatFromJSONTyped(json, false);
}

export function BpnFeatureVersionStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnFeatureVersionStat {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'featureStats': StatsFromJSON(json['featureStats']),
        'versionStats': StatsFromJSON(json['versionStats']),
        'taskStats': ((json['taskStats'] as Array<any>).map(TaskStatsFromJSON)),
    };
}

export function BpnFeatureVersionStatToJSON(value?: BpnFeatureVersionStat | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'featureStats': StatsToJSON(value['featureStats']),
        'versionStats': StatsToJSON(value['versionStats']),
        'taskStats': ((value['taskStats'] as Array<any>).map(TaskStatsToJSON)),
    };
}

