/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BpnPosition } from './BpnPosition';
import {
    BpnPositionFromJSON,
    BpnPositionFromJSONTyped,
    BpnPositionToJSON,
} from './BpnPosition';
import type { ConnectionWaypoints } from './ConnectionWaypoints';
import {
    ConnectionWaypointsFromJSON,
    ConnectionWaypointsFromJSONTyped,
    ConnectionWaypointsToJSON,
} from './ConnectionWaypoints';

/**
 * 
 * @export
 * @interface BpnFeatureDiagram
 */
export interface BpnFeatureDiagram {
    /**
     * 
     * @type {Array<BpnPosition>}
     * @memberof BpnFeatureDiagram
     */
    bpnPositions?: Array<BpnPosition>;
    /**
     * 
     * @type {Array<ConnectionWaypoints>}
     * @memberof BpnFeatureDiagram
     */
    bpnConnectionWaypoints?: Array<ConnectionWaypoints>;
}

/**
 * Check if a given object implements the BpnFeatureDiagram interface.
 */
export function instanceOfBpnFeatureDiagram(value: object): value is BpnFeatureDiagram {
    return true;
}

export function BpnFeatureDiagramFromJSON(json: any): BpnFeatureDiagram {
    return BpnFeatureDiagramFromJSONTyped(json, false);
}

export function BpnFeatureDiagramFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnFeatureDiagram {
    if (json == null) {
        return json;
    }
    return {
        
        'bpnPositions': json['bpnPositions'] == null ? undefined : ((json['bpnPositions'] as Array<any>).map(BpnPositionFromJSON)),
        'bpnConnectionWaypoints': json['bpnConnectionWaypoints'] == null ? undefined : ((json['bpnConnectionWaypoints'] as Array<any>).map(ConnectionWaypointsFromJSON)),
    };
}

export function BpnFeatureDiagramToJSON(value?: BpnFeatureDiagram | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bpnPositions': value['bpnPositions'] == null ? undefined : ((value['bpnPositions'] as Array<any>).map(BpnPositionToJSON)),
        'bpnConnectionWaypoints': value['bpnConnectionWaypoints'] == null ? undefined : ((value['bpnConnectionWaypoints'] as Array<any>).map(ConnectionWaypointsToJSON)),
    };
}

