/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';

/**
 * 
 * @export
 * @interface BpnPosition
 */
export interface BpnPosition {
    /**
     * 
     * @type {string}
     * @memberof BpnPosition
     */
    id: string;
    /**
     * 
     * @type {Position}
     * @memberof BpnPosition
     */
    position: Position;
}

/**
 * Check if a given object implements the BpnPosition interface.
 */
export function instanceOfBpnPosition(value: object): value is BpnPosition {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function BpnPositionFromJSON(json: any): BpnPosition {
    return BpnPositionFromJSONTyped(json, false);
}

export function BpnPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnPosition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'position': PositionFromJSON(json['position']),
    };
}

export function BpnPositionToJSON(value?: BpnPosition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'position': PositionToJSON(value['position']),
    };
}

