/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextDetails } from './ContextDetails';
import {
    ContextDetailsFromJSON,
    ContextDetailsFromJSONTyped,
    ContextDetailsToJSON,
} from './ContextDetails';

/**
 * 
 * @export
 * @interface BpnSystem
 */
export interface BpnSystem {
    /**
     * 
     * @type {string}
     * @memberof BpnSystem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BpnSystem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BpnSystem
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof BpnSystem
     */
    createdTimestamp: Date;
    /**
     * 
     * @type {Date}
     * @memberof BpnSystem
     */
    lastUpdatedTimestamp: Date;
    /**
     * 
     * @type {Array<ContextDetails>}
     * @memberof BpnSystem
     */
    containers: Array<ContextDetails>;
    /**
     * 
     * @type {string}
     * @memberof BpnSystem
     */
    c4ContainerDiagramSvg: string;
}

/**
 * Check if a given object implements the BpnSystem interface.
 */
export function instanceOfBpnSystem(value: object): value is BpnSystem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('createdTimestamp' in value) || value['createdTimestamp'] === undefined) return false;
    if (!('lastUpdatedTimestamp' in value) || value['lastUpdatedTimestamp'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    if (!('c4ContainerDiagramSvg' in value) || value['c4ContainerDiagramSvg'] === undefined) return false;
    return true;
}

export function BpnSystemFromJSON(json: any): BpnSystem {
    return BpnSystemFromJSONTyped(json, false);
}

export function BpnSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BpnSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'createdTimestamp': (new Date(json['createdTimestamp'])),
        'lastUpdatedTimestamp': (new Date(json['lastUpdatedTimestamp'])),
        'containers': ((json['containers'] as Array<any>).map(ContextDetailsFromJSON)),
        'c4ContainerDiagramSvg': json['c4ContainerDiagramSvg'],
    };
}

export function BpnSystemToJSON(value?: BpnSystem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'createdTimestamp': ((value['createdTimestamp']).toISOString()),
        'lastUpdatedTimestamp': ((value['lastUpdatedTimestamp']).toISOString()),
        'containers': ((value['containers'] as Array<any>).map(ContextDetailsToJSON)),
        'c4ContainerDiagramSvg': value['c4ContainerDiagramSvg'],
    };
}

