/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCase } from './TestCase';
import {
    TestCaseFromJSON,
    TestCaseFromJSONTyped,
    TestCaseToJSON,
} from './TestCase';
import type { RecordDefinition } from './RecordDefinition';
import {
    RecordDefinitionFromJSON,
    RecordDefinitionFromJSONTyped,
    RecordDefinitionToJSON,
} from './RecordDefinition';

/**
 * 
 * @export
 * @interface CodeTask
 */
export interface CodeTask {
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    businessPurpose: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    behavioralGoal: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    input?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    output?: string | null;
    /**
     * 
     * @type {Array<TestCase>}
     * @memberof CodeTask
     */
    testCases: Array<TestCase>;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    serviceDependency: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    namedConfiguration: string;
    /**
     * 
     * @type {Array<RecordDefinition>}
     * @memberof CodeTask
     */
    recordTypes: Array<RecordDefinition>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CodeTask
     */
    validDatatypes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    recordsAsCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeTask
     */
    methodSignatureAsCode?: string;
}

/**
 * Check if a given object implements the CodeTask interface.
 */
export function instanceOfCodeTask(value: object): value is CodeTask {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessPurpose' in value) || value['businessPurpose'] === undefined) return false;
    if (!('behavioralGoal' in value) || value['behavioralGoal'] === undefined) return false;
    if (!('testCases' in value) || value['testCases'] === undefined) return false;
    if (!('serviceDependency' in value) || value['serviceDependency'] === undefined) return false;
    if (!('namedConfiguration' in value) || value['namedConfiguration'] === undefined) return false;
    if (!('recordTypes' in value) || value['recordTypes'] === undefined) return false;
    if (!('validDatatypes' in value) || value['validDatatypes'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function CodeTaskFromJSON(json: any): CodeTask {
    return CodeTaskFromJSONTyped(json, false);
}

export function CodeTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'businessPurpose': json['businessPurpose'],
        'behavioralGoal': json['behavioralGoal'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'testCases': ((json['testCases'] as Array<any>).map(TestCaseFromJSON)),
        'serviceDependency': json['serviceDependency'],
        'namedConfiguration': json['namedConfiguration'],
        'recordTypes': ((json['recordTypes'] as Array<any>).map(RecordDefinitionFromJSON)),
        'validDatatypes': json['validDatatypes'],
        'code': json['code'],
        'recordsAsCode': json['recordsAsCode'] == null ? undefined : json['recordsAsCode'],
        'methodSignatureAsCode': json['methodSignatureAsCode'] == null ? undefined : json['methodSignatureAsCode'],
    };
}

export function CodeTaskToJSON(value?: CodeTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'businessPurpose': value['businessPurpose'],
        'behavioralGoal': value['behavioralGoal'],
        'input': value['input'],
        'output': value['output'],
        'testCases': ((value['testCases'] as Array<any>).map(TestCaseToJSON)),
        'serviceDependency': value['serviceDependency'],
        'namedConfiguration': value['namedConfiguration'],
        'recordTypes': ((value['recordTypes'] as Array<any>).map(RecordDefinitionToJSON)),
        'validDatatypes': value['validDatatypes'],
        'code': value['code'],
        'recordsAsCode': value['recordsAsCode'],
        'methodSignatureAsCode': value['methodSignatureAsCode'],
    };
}

