/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeSnippet
 */
export interface CodeSnippet {
    /**
     * 
     * @type {string}
     * @memberof CodeSnippet
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CodeSnippet
     */
    snippet?: string;
}

/**
 * Check if a given object implements the CodeSnippet interface.
 */
export function instanceOfCodeSnippet(value: object): value is CodeSnippet {
    return true;
}

export function CodeSnippetFromJSON(json: any): CodeSnippet {
    return CodeSnippetFromJSONTyped(json, false);
}

export function CodeSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeSnippet {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
    };
}

export function CodeSnippetToJSON(value?: CodeSnippet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'snippet': value['snippet'],
    };
}

