/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompileError
 */
export interface CompileError {
    /**
     * 
     * @type {string}
     * @memberof CompileError
     */
    errorMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof CompileError
     */
    lineNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CompileError
     */
    columnNumber?: number;
}

/**
 * Check if a given object implements the CompileError interface.
 */
export function instanceOfCompileError(value: object): value is CompileError {
    return true;
}

export function CompileErrorFromJSON(json: any): CompileError {
    return CompileErrorFromJSONTyped(json, false);
}

export function CompileErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompileError {
    if (json == null) {
        return json;
    }
    return {
        
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
        'columnNumber': json['columnNumber'] == null ? undefined : json['columnNumber'],
    };
}

export function CompileErrorToJSON(value?: CompileError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorMessage': value['errorMessage'],
        'lineNumber': value['lineNumber'],
        'columnNumber': value['columnNumber'],
    };
}

