/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsumeComponent
 */
export interface ConsumeComponent {
    /**
     * 
     * @type {string}
     * @memberof ConsumeComponent
     */
    componentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsumeComponent
     */
    consumeText?: string | null;
}

/**
 * Check if a given object implements the ConsumeComponent interface.
 */
export function instanceOfConsumeComponent(value: object): value is ConsumeComponent {
    return true;
}

export function ConsumeComponentFromJSON(json: any): ConsumeComponent {
    return ConsumeComponentFromJSONTyped(json, false);
}

export function ConsumeComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsumeComponent {
    if (json == null) {
        return json;
    }
    return {
        
        'componentId': json['componentId'] == null ? undefined : json['componentId'],
        'consumeText': json['consumeText'] == null ? undefined : json['consumeText'],
    };
}

export function ConsumeComponentToJSON(value?: ConsumeComponent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'componentId': value['componentId'],
        'consumeText': value['consumeText'],
    };
}

