/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContextDetails
 */
export interface ContextDetails {
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    description: string;
}

/**
 * Check if a given object implements the ContextDetails interface.
 */
export function instanceOfContextDetails(value: object): value is ContextDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ContextDetailsFromJSON(json: any): ContextDetails {
    return ContextDetailsFromJSONTyped(json, false);
}

export function ContextDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function ContextDetailsToJSON(value?: ContextDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

