/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Persona } from './Persona';
import {
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
} from './Persona';

/**
 * 
 * @export
 * @interface ContextDetails
 */
export interface ContextDetails {
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContextDetails
     */
    description: string;
    /**
     * 
     * @type {Array<Persona>}
     * @memberof ContextDetails
     */
    personas: Array<Persona>;
}

/**
 * Check if a given object implements the ContextDetails interface.
 */
export function instanceOfContextDetails(value: object): value is ContextDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('personas' in value) || value['personas'] === undefined) return false;
    return true;
}

export function ContextDetailsFromJSON(json: any): ContextDetails {
    return ContextDetailsFromJSONTyped(json, false);
}

export function ContextDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'personas': ((json['personas'] as Array<any>).map(PersonaFromJSON)),
    };
}

export function ContextDetailsToJSON(value?: ContextDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'personas': ((value['personas'] as Array<any>).map(PersonaToJSON)),
    };
}

