/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateContainerBody
 */
export interface CreateContainerBody {
    /**
     * 
     * @type {string}
     * @memberof CreateContainerBody
     */
    systemId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContainerBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateContainerBody
     */
    description: string;
}

/**
 * Check if a given object implements the CreateContainerBody interface.
 */
export function instanceOfCreateContainerBody(value: object): value is CreateContainerBody {
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateContainerBodyFromJSON(json: any): CreateContainerBody {
    return CreateContainerBodyFromJSONTyped(json, false);
}

export function CreateContainerBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContainerBody {
    if (json == null) {
        return json;
    }
    return {
        
        'systemId': json['systemId'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function CreateContainerBodyToJSON(value?: CreateContainerBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'systemId': value['systemId'],
        'name': value['name'],
        'description': value['description'],
    };
}

