/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSolutionBody
 */
export interface CreateSolutionBody {
    /**
     * 
     * @type {string}
     * @memberof CreateSolutionBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSolutionBody
     */
    description: string;
}

/**
 * Check if a given object implements the CreateSolutionBody interface.
 */
export function instanceOfCreateSolutionBody(value: object): value is CreateSolutionBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateSolutionBodyFromJSON(json: any): CreateSolutionBody {
    return CreateSolutionBodyFromJSONTyped(json, false);
}

export function CreateSolutionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolutionBody {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function CreateSolutionBodyToJSON(value?: CreateSolutionBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

