/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataDefinition
 */
export interface DataDefinition {
    /**
     * 
     * @type {string}
     * @memberof DataDefinition
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DataDefinition
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DataDefinition
     */
    isCollection?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DataDefinition
     */
    isMandatory?: boolean;
}

/**
 * Check if a given object implements the DataDefinition interface.
 */
export function instanceOfDataDefinition(value: object): value is DataDefinition {
    return true;
}

export function DataDefinitionFromJSON(json: any): DataDefinition {
    return DataDefinitionFromJSONTyped(json, false);
}

export function DataDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'isCollection': json['isCollection'] == null ? undefined : json['isCollection'],
        'isMandatory': json['isMandatory'] == null ? undefined : json['isMandatory'],
    };
}

export function DataDefinitionToJSON(value?: DataDefinition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'isCollection': value['isCollection'],
        'isMandatory': value['isMandatory'],
    };
}

