/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAssertionOnTask
 */
export interface DeleteAssertionOnTask {
    /**
     * 
     * @type {string}
     * @memberof DeleteAssertionOnTask
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteAssertionOnTask
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteAssertionOnTask
     */
    assertionId: string;
}

/**
 * Check if a given object implements the DeleteAssertionOnTask interface.
 */
export function instanceOfDeleteAssertionOnTask(value: object): value is DeleteAssertionOnTask {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('assertionId' in value) || value['assertionId'] === undefined) return false;
    return true;
}

export function DeleteAssertionOnTaskFromJSON(json: any): DeleteAssertionOnTask {
    return DeleteAssertionOnTaskFromJSONTyped(json, false);
}

export function DeleteAssertionOnTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAssertionOnTask {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'assertionId': json['assertionId'],
    };
}

export function DeleteAssertionOnTaskToJSON(value?: DeleteAssertionOnTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'assertionId': value['assertionId'],
    };
}

