/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteRecordOnTaskBody
 */
export interface DeleteRecordOnTaskBody {
    /**
     * 
     * @type {string}
     * @memberof DeleteRecordOnTaskBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteRecordOnTaskBody
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteRecordOnTaskBody
     */
    name: string;
}

/**
 * Check if a given object implements the DeleteRecordOnTaskBody interface.
 */
export function instanceOfDeleteRecordOnTaskBody(value: object): value is DeleteRecordOnTaskBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeleteRecordOnTaskBodyFromJSON(json: any): DeleteRecordOnTaskBody {
    return DeleteRecordOnTaskBodyFromJSONTyped(json, false);
}

export function DeleteRecordOnTaskBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRecordOnTaskBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'name': json['name'],
    };
}

export function DeleteRecordOnTaskBodyToJSON(value?: DeleteRecordOnTaskBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'name': value['name'],
    };
}

