/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Environment = {
    Development: 'Development',
    Testing: 'Testing',
    Staging: 'Staging',
    Production: 'Production'
} as const;
export type Environment = typeof Environment[keyof typeof Environment];


export function instanceOfEnvironment(value: any): boolean {
    for (const key in Environment) {
        if (Object.prototype.hasOwnProperty.call(Environment, key)) {
            if (Environment[key as keyof typeof Environment] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EnvironmentFromJSON(json: any): Environment {
    return EnvironmentFromJSONTyped(json, false);
}

export function EnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Environment {
    return json as Environment;
}

export function EnvironmentToJSON(value?: Environment | null): any {
    return value as any;
}

