/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Environment } from './Environment';
import {
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
} from './Environment';
import type { FeatureStats } from './FeatureStats';
import {
    FeatureStatsFromJSON,
    FeatureStatsFromJSONTyped,
    FeatureStatsToJSON,
} from './FeatureStats';

/**
 * 
 * @export
 * @interface FeatureRevisions
 */
export interface FeatureRevisions {
    /**
     * 
     * @type {string}
     * @memberof FeatureRevisions
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FeatureRevisions
     */
    revision: number;
    /**
     * 
     * @type {Array<Environment>}
     * @memberof FeatureRevisions
     */
    environments: Array<Environment>;
    /**
     * 
     * @type {FeatureStats}
     * @memberof FeatureRevisions
     */
    stats: FeatureStats;
}

/**
 * Check if a given object implements the FeatureRevisions interface.
 */
export function instanceOfFeatureRevisions(value: object): value is FeatureRevisions {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('environments' in value) || value['environments'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    return true;
}

export function FeatureRevisionsFromJSON(json: any): FeatureRevisions {
    return FeatureRevisionsFromJSONTyped(json, false);
}

export function FeatureRevisionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureRevisions {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'revision': json['revision'],
        'environments': ((json['environments'] as Array<any>).map(EnvironmentFromJSON)),
        'stats': FeatureStatsFromJSON(json['stats']),
    };
}

export function FeatureRevisionsToJSON(value?: FeatureRevisions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'revision': value['revision'],
        'environments': ((value['environments'] as Array<any>).map(EnvironmentToJSON)),
        'stats': FeatureStatsToJSON(value['stats']),
    };
}

