/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureVersion } from './FeatureVersion';
import {
    FeatureVersionFromJSON,
    FeatureVersionFromJSONTyped,
    FeatureVersionToJSON,
} from './FeatureVersion';

/**
 * 
 * @export
 * @interface FeatureDetails
 */
export interface FeatureDetails {
    /**
     * 
     * @type {string}
     * @memberof FeatureDetails
     */
    id: string;
    /**
     * 
     * @type {Array<FeatureVersion>}
     * @memberof FeatureDetails
     */
    versions: Array<FeatureVersion>;
}

/**
 * Check if a given object implements the FeatureDetails interface.
 */
export function instanceOfFeatureDetails(value: object): value is FeatureDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function FeatureDetailsFromJSON(json: any): FeatureDetails {
    return FeatureDetailsFromJSONTyped(json, false);
}

export function FeatureDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'versions': ((json['versions'] as Array<any>).map(FeatureVersionFromJSON)),
    };
}

export function FeatureDetailsToJSON(value?: FeatureDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'versions': ((value['versions'] as Array<any>).map(FeatureVersionToJSON)),
    };
}

