/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureStats
 */
export interface FeatureStats {
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    invocationCount: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    invocationErrorCount: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    invocationCompletedCount: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    invocationsInProgressCount: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    totalDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    maxDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    avgDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof FeatureStats
     */
    minDurationMs: number;
    /**
     * 
     * @type {Date}
     * @memberof FeatureStats
     */
    lastUsed: Date;
}

/**
 * Check if a given object implements the FeatureStats interface.
 */
export function instanceOfFeatureStats(value: object): value is FeatureStats {
    if (!('invocationCount' in value) || value['invocationCount'] === undefined) return false;
    if (!('invocationErrorCount' in value) || value['invocationErrorCount'] === undefined) return false;
    if (!('invocationCompletedCount' in value) || value['invocationCompletedCount'] === undefined) return false;
    if (!('invocationsInProgressCount' in value) || value['invocationsInProgressCount'] === undefined) return false;
    if (!('totalDurationMs' in value) || value['totalDurationMs'] === undefined) return false;
    if (!('maxDurationMs' in value) || value['maxDurationMs'] === undefined) return false;
    if (!('avgDurationMs' in value) || value['avgDurationMs'] === undefined) return false;
    if (!('minDurationMs' in value) || value['minDurationMs'] === undefined) return false;
    if (!('lastUsed' in value) || value['lastUsed'] === undefined) return false;
    return true;
}

export function FeatureStatsFromJSON(json: any): FeatureStats {
    return FeatureStatsFromJSONTyped(json, false);
}

export function FeatureStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureStats {
    if (json == null) {
        return json;
    }
    return {
        
        'invocationCount': json['invocationCount'],
        'invocationErrorCount': json['invocationErrorCount'],
        'invocationCompletedCount': json['invocationCompletedCount'],
        'invocationsInProgressCount': json['invocationsInProgressCount'],
        'totalDurationMs': json['totalDurationMs'],
        'maxDurationMs': json['maxDurationMs'],
        'avgDurationMs': json['avgDurationMs'],
        'minDurationMs': json['minDurationMs'],
        'lastUsed': (new Date(json['lastUsed'])),
    };
}

export function FeatureStatsToJSON(value?: FeatureStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invocationCount': value['invocationCount'],
        'invocationErrorCount': value['invocationErrorCount'],
        'invocationCompletedCount': value['invocationCompletedCount'],
        'invocationsInProgressCount': value['invocationsInProgressCount'],
        'totalDurationMs': value['totalDurationMs'],
        'maxDurationMs': value['maxDurationMs'],
        'avgDurationMs': value['avgDurationMs'],
        'minDurationMs': value['minDurationMs'],
        'lastUsed': ((value['lastUsed']).toISOString()),
    };
}

