/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureRevisions } from './FeatureRevisions';
import {
    FeatureRevisionsFromJSON,
    FeatureRevisionsFromJSONTyped,
    FeatureRevisionsToJSON,
} from './FeatureRevisions';
import type { Persona3 } from './Persona3';
import {
    Persona3FromJSON,
    Persona3FromJSONTyped,
    Persona3ToJSON,
} from './Persona3';

/**
 * 
 * @export
 * @interface FeatureDetails
 */
export interface FeatureDetails {
    /**
     * 
     * @type {string}
     * @memberof FeatureDetails
     */
    id: string;
    /**
     * 
     * @type {Array<FeatureRevisions>}
     * @memberof FeatureDetails
     */
    revisions: Array<FeatureRevisions>;
    /**
     * 
     * @type {Array<Persona3>}
     * @memberof FeatureDetails
     */
    personas: Array<Persona3>;
}

/**
 * Check if a given object implements the FeatureDetails interface.
 */
export function instanceOfFeatureDetails(value: object): value is FeatureDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('revisions' in value) || value['revisions'] === undefined) return false;
    if (!('personas' in value) || value['personas'] === undefined) return false;
    return true;
}

export function FeatureDetailsFromJSON(json: any): FeatureDetails {
    return FeatureDetailsFromJSONTyped(json, false);
}

export function FeatureDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'revisions': ((json['revisions'] as Array<any>).map(FeatureRevisionsFromJSON)),
        'personas': ((json['personas'] as Array<any>).map(Persona3FromJSON)),
    };
}

export function FeatureDetailsToJSON(value?: FeatureDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'revisions': ((value['revisions'] as Array<any>).map(FeatureRevisionsToJSON)),
        'personas': ((value['personas'] as Array<any>).map(Persona3ToJSON)),
    };
}

