/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Persona3
 */
export interface Persona3 {
    /**
     * 
     * @type {string}
     * @memberof Persona3
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Persona3
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Persona3
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Persona3
     */
    relationToComponent: string;
}

/**
 * Check if a given object implements the Persona3 interface.
 */
export function instanceOfPersona3(value: object): value is Persona3 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('relationToComponent' in value) || value['relationToComponent'] === undefined) return false;
    return true;
}

export function Persona3FromJSON(json: any): Persona3 {
    return Persona3FromJSONTyped(json, false);
}

export function Persona3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Persona3 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'relationToComponent': json['relationToComponent'],
    };
}

export function Persona3ToJSON(value?: Persona3 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'relationToComponent': value['relationToComponent'],
    };
}

