/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsumeComponent } from './ConsumeComponent';
import {
    ConsumeComponentFromJSON,
    ConsumeComponentFromJSONTyped,
    ConsumeComponentToJSON,
} from './ConsumeComponent';

/**
 * 
 * @export
 * @interface Persona4
 */
export interface Persona4 {
    /**
     * 
     * @type {string}
     * @memberof Persona4
     */
    id: string;
    /**
     * 
     * @type {Array<ConsumeComponent>}
     * @memberof Persona4
     */
    components: Array<ConsumeComponent>;
    /**
     * 
     * @type {string}
     * @memberof Persona4
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Persona4
     */
    description: string;
}

/**
 * Check if a given object implements the Persona4 interface.
 */
export function instanceOfPersona4(value: object): value is Persona4 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('components' in value) || value['components'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function Persona4FromJSON(json: any): Persona4 {
    return Persona4FromJSONTyped(json, false);
}

export function Persona4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Persona4 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'components': ((json['components'] as Array<any>).map(ConsumeComponentFromJSON)),
        'name': json['name'],
        'description': json['description'],
    };
}

export function Persona4ToJSON(value?: Persona4 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'components': ((value['components'] as Array<any>).map(ConsumeComponentToJSON)),
        'name': value['name'],
        'description': value['description'],
    };
}

