/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Persona2
 */
export interface Persona2 {
    /**
     * 
     * @type {string}
     * @memberof Persona2
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Persona2
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Persona2
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Persona2
     */
    relationToContainer: string;
}

/**
 * Check if a given object implements the Persona2 interface.
 */
export function instanceOfPersona2(value: object): value is Persona2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('relationToContainer' in value) || value['relationToContainer'] === undefined) return false;
    return true;
}

export function Persona2FromJSON(json: any): Persona2 {
    return Persona2FromJSONTyped(json, false);
}

export function Persona2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Persona2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'relationToContainer': json['relationToContainer'],
    };
}

export function Persona2ToJSON(value?: Persona2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'relationToContainer': value['relationToContainer'],
    };
}

