/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReleaseFeatureBody
 */
export interface ReleaseFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof ReleaseFeatureBody
     */
    featureId: string;
}

/**
 * Check if a given object implements the ReleaseFeatureBody interface.
 */
export function instanceOfReleaseFeatureBody(value: object): value is ReleaseFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    return true;
}

export function ReleaseFeatureBodyFromJSON(json: any): ReleaseFeatureBody {
    return ReleaseFeatureBodyFromJSONTyped(json, false);
}

export function ReleaseFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
    };
}

export function ReleaseFeatureBodyToJSON(value?: ReleaseFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
    };
}

