/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveNamedConfigurationBody
 */
export interface RemoveNamedConfigurationBody {
    /**
     * 
     * @type {string}
     * @memberof RemoveNamedConfigurationBody
     */
    namedConfigurationId: string;
}

/**
 * Check if a given object implements the RemoveNamedConfigurationBody interface.
 */
export function instanceOfRemoveNamedConfigurationBody(value: object): value is RemoveNamedConfigurationBody {
    if (!('namedConfigurationId' in value) || value['namedConfigurationId'] === undefined) return false;
    return true;
}

export function RemoveNamedConfigurationBodyFromJSON(json: any): RemoveNamedConfigurationBody {
    return RemoveNamedConfigurationBodyFromJSONTyped(json, false);
}

export function RemoveNamedConfigurationBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveNamedConfigurationBody {
    if (json == null) {
        return json;
    }
    return {
        
        'namedConfigurationId': json['namedConfigurationId'],
    };
}

export function RemoveNamedConfigurationBodyToJSON(value?: RemoveNamedConfigurationBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'namedConfigurationId': value['namedConfigurationId'],
    };
}

