/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveTestCaseFromTask
 */
export interface RemoveTestCaseFromTask {
    /**
     * 
     * @type {string}
     * @memberof RemoveTestCaseFromTask
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof RemoveTestCaseFromTask
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof RemoveTestCaseFromTask
     */
    assertionId: string;
}

/**
 * Check if a given object implements the RemoveTestCaseFromTask interface.
 */
export function instanceOfRemoveTestCaseFromTask(value: object): value is RemoveTestCaseFromTask {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('assertionId' in value) || value['assertionId'] === undefined) return false;
    return true;
}

export function RemoveTestCaseFromTaskFromJSON(json: any): RemoveTestCaseFromTask {
    return RemoveTestCaseFromTaskFromJSONTyped(json, false);
}

export function RemoveTestCaseFromTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveTestCaseFromTask {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'assertionId': json['assertionId'],
    };
}

export function RemoveTestCaseFromTaskToJSON(value?: RemoveTestCaseFromTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'assertionId': value['assertionId'],
    };
}

