/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetDraftFeatureBody
 */
export interface ResetDraftFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof ResetDraftFeatureBody
     */
    featureId: string;
}

/**
 * Check if a given object implements the ResetDraftFeatureBody interface.
 */
export function instanceOfResetDraftFeatureBody(value: object): value is ResetDraftFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    return true;
}

export function ResetDraftFeatureBodyFromJSON(json: any): ResetDraftFeatureBody {
    return ResetDraftFeatureBodyFromJSONTyped(json, false);
}

export function ResetDraftFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetDraftFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
    };
}

export function ResetDraftFeatureBodyToJSON(value?: ResetDraftFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
    };
}

