/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Scope = {
    Internal: 'Internal',
    External: 'External'
} as const;
export type Scope = typeof Scope[keyof typeof Scope];


export function instanceOfScope(value: any): boolean {
    for (const key in Scope) {
        if (Object.prototype.hasOwnProperty.call(Scope, key)) {
            if (Scope[key as keyof typeof Scope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScopeFromJSON(json: any): Scope {
    return ScopeFromJSONTyped(json, false);
}

export function ScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scope {
    return json as Scope;
}

export function ScopeToJSON(value?: Scope | null): any {
    return value as any;
}

