/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemDetails
 */
export interface SystemDetails {
    /**
     * 
     * @type {string}
     * @memberof SystemDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SystemDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SystemDetails
     */
    description: string;
}

/**
 * Check if a given object implements the SystemDetails interface.
 */
export function instanceOfSystemDetails(value: object): value is SystemDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function SystemDetailsFromJSON(json: any): SystemDetails {
    return SystemDetailsFromJSONTyped(json, false);
}

export function SystemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function SystemDetailsToJSON(value?: SystemDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

