/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Task3
 */
export interface Task3 {
    /**
     * 
     * @type {string}
     * @memberof Task3
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Task3
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task3
     */
    serviceDependencyId?: string;
    /**
     * 
     * @type {string}
     * @memberof Task3
     */
    namedConfigurationName?: string | null;
}

/**
 * Check if a given object implements the Task3 interface.
 */
export function instanceOfTask3(value: object): value is Task3 {
    return true;
}

export function Task3FromJSON(json: any): Task3 {
    return Task3FromJSONTyped(json, false);
}

export function Task3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Task3 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'serviceDependencyId': json['serviceDependencyId'] == null ? undefined : json['serviceDependencyId'],
        'namedConfigurationName': json['namedConfigurationName'] == null ? undefined : json['namedConfigurationName'],
    };
}

export function Task3ToJSON(value?: Task3 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'serviceDependencyId': value['serviceDependencyId'],
        'namedConfigurationName': value['namedConfigurationName'],
    };
}

