/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskStats
 */
export interface TaskStats {
    /**
     * 
     * @type {string}
     * @memberof TaskStats
     */
    task: string;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    invocationCount: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    invocationErrorCount: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    invocationCompletedCount: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    invocationsInProgressCount: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    totalDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    maxDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    avgDurationMs: number;
    /**
     * 
     * @type {number}
     * @memberof TaskStats
     */
    minDurationMs: number;
    /**
     * 
     * @type {Date}
     * @memberof TaskStats
     */
    lastUsed?: Date | null;
}

/**
 * Check if a given object implements the TaskStats interface.
 */
export function instanceOfTaskStats(value: object): value is TaskStats {
    if (!('task' in value) || value['task'] === undefined) return false;
    if (!('invocationCount' in value) || value['invocationCount'] === undefined) return false;
    if (!('invocationErrorCount' in value) || value['invocationErrorCount'] === undefined) return false;
    if (!('invocationCompletedCount' in value) || value['invocationCompletedCount'] === undefined) return false;
    if (!('invocationsInProgressCount' in value) || value['invocationsInProgressCount'] === undefined) return false;
    if (!('totalDurationMs' in value) || value['totalDurationMs'] === undefined) return false;
    if (!('maxDurationMs' in value) || value['maxDurationMs'] === undefined) return false;
    if (!('avgDurationMs' in value) || value['avgDurationMs'] === undefined) return false;
    if (!('minDurationMs' in value) || value['minDurationMs'] === undefined) return false;
    return true;
}

export function TaskStatsFromJSON(json: any): TaskStats {
    return TaskStatsFromJSONTyped(json, false);
}

export function TaskStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStats {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'],
        'invocationCount': json['invocationCount'],
        'invocationErrorCount': json['invocationErrorCount'],
        'invocationCompletedCount': json['invocationCompletedCount'],
        'invocationsInProgressCount': json['invocationsInProgressCount'],
        'totalDurationMs': json['totalDurationMs'],
        'maxDurationMs': json['maxDurationMs'],
        'avgDurationMs': json['avgDurationMs'],
        'minDurationMs': json['minDurationMs'],
        'lastUsed': json['lastUsed'] == null ? undefined : (new Date(json['lastUsed'])),
    };
}

export function TaskStatsToJSON(value?: TaskStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'task': value['task'],
        'invocationCount': value['invocationCount'],
        'invocationErrorCount': value['invocationErrorCount'],
        'invocationCompletedCount': value['invocationCompletedCount'],
        'invocationsInProgressCount': value['invocationsInProgressCount'],
        'totalDurationMs': value['totalDurationMs'],
        'maxDurationMs': value['maxDurationMs'],
        'avgDurationMs': value['avgDurationMs'],
        'minDurationMs': value['minDurationMs'],
        'lastUsed': value['lastUsed'] == null ? undefined : ((value['lastUsed'] as any).toISOString()),
    };
}

