/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordDefinition } from './RecordDefinition';
import {
    RecordDefinitionFromJSON,
    RecordDefinitionFromJSONTyped,
    RecordDefinitionToJSON,
} from './RecordDefinition';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    businessPurpose: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    behavioralGoal: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    input?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    output?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    namedConfigurationId?: string | null;
    /**
     * 
     * @type {Array<RecordDefinition>}
     * @memberof Task
     */
    recordTypes: Array<RecordDefinition>;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessPurpose' in value) || value['businessPurpose'] === undefined) return false;
    if (!('behavioralGoal' in value) || value['behavioralGoal'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('recordTypes' in value) || value['recordTypes'] === undefined) return false;
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'businessPurpose': json['businessPurpose'],
        'behavioralGoal': json['behavioralGoal'],
        'input': json['input'] == null ? undefined : json['input'],
        'output': json['output'] == null ? undefined : json['output'],
        'code': json['code'],
        'namedConfigurationId': json['namedConfigurationId'] == null ? undefined : json['namedConfigurationId'],
        'recordTypes': ((json['recordTypes'] as Array<any>).map(RecordDefinitionFromJSON)),
    };
}

export function TaskToJSON(value?: Task | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'businessPurpose': value['businessPurpose'],
        'behavioralGoal': value['behavioralGoal'],
        'input': value['input'],
        'output': value['output'],
        'code': value['code'],
        'namedConfigurationId': value['namedConfigurationId'],
        'recordTypes': ((value['recordTypes'] as Array<any>).map(RecordDefinitionToJSON)),
    };
}

