/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssertDefinition } from './AssertDefinition';
import {
    AssertDefinitionFromJSON,
    AssertDefinitionFromJSONTyped,
    AssertDefinitionToJSON,
} from './AssertDefinition';

/**
 * 
 * @export
 * @interface TestCase
 */
export interface TestCase {
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof TestCase
     */
    input?: any | null;
    /**
     * 
     * @type {Array<AssertDefinition>}
     * @memberof TestCase
     */
    asserts?: Array<AssertDefinition>;
}

/**
 * Check if a given object implements the TestCase interface.
 */
export function instanceOfTestCase(value: object): value is TestCase {
    return true;
}

export function TestCaseFromJSON(json: any): TestCase {
    return TestCaseFromJSONTyped(json, false);
}

export function TestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCase {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'input': json['input'] == null ? undefined : json['input'],
        'asserts': json['asserts'] == null ? undefined : ((json['asserts'] as Array<any>).map(AssertDefinitionFromJSON)),
    };
}

export function TestCaseToJSON(value?: TestCase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'input': value['input'],
        'asserts': value['asserts'] == null ? undefined : ((value['asserts'] as Array<any>).map(AssertDefinitionToJSON)),
    };
}

