/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCodeOnTaskBody
 */
export interface UpdateCodeOnTaskBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateCodeOnTaskBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCodeOnTaskBody
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCodeOnTaskBody
     */
    code: string;
}

/**
 * Check if a given object implements the UpdateCodeOnTaskBody interface.
 */
export function instanceOfUpdateCodeOnTaskBody(value: object): value is UpdateCodeOnTaskBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function UpdateCodeOnTaskBodyFromJSON(json: any): UpdateCodeOnTaskBody {
    return UpdateCodeOnTaskBodyFromJSONTyped(json, false);
}

export function UpdateCodeOnTaskBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCodeOnTaskBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'code': json['code'],
    };
}

export function UpdateCodeOnTaskBodyToJSON(value?: UpdateCodeOnTaskBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'code': value['code'],
    };
}

