/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCase } from './TestCase';
import {
    TestCaseFromJSON,
    TestCaseFromJSONTyped,
    TestCaseToJSON,
} from './TestCase';

/**
 * 
 * @export
 * @interface UpdateAssertionOnTaskBody
 */
export interface UpdateAssertionOnTaskBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateAssertionOnTaskBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssertionOnTaskBody
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAssertionOnTaskBody
     */
    assertionId: string;
    /**
     * 
     * @type {TestCase}
     * @memberof UpdateAssertionOnTaskBody
     */
    testCase: TestCase;
}

/**
 * Check if a given object implements the UpdateAssertionOnTaskBody interface.
 */
export function instanceOfUpdateAssertionOnTaskBody(value: object): value is UpdateAssertionOnTaskBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('assertionId' in value) || value['assertionId'] === undefined) return false;
    if (!('testCase' in value) || value['testCase'] === undefined) return false;
    return true;
}

export function UpdateAssertionOnTaskBodyFromJSON(json: any): UpdateAssertionOnTaskBody {
    return UpdateAssertionOnTaskBodyFromJSONTyped(json, false);
}

export function UpdateAssertionOnTaskBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAssertionOnTaskBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'assertionId': json['assertionId'],
        'testCase': TestCaseFromJSON(json['testCase']),
    };
}

export function UpdateAssertionOnTaskBodyToJSON(value?: UpdateAssertionOnTaskBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'assertionId': value['assertionId'],
        'testCase': TestCaseToJSON(value['testCase']),
    };
}

