/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskPurposeFeatureBody
 */
export interface UpdateTaskPurposeFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskPurposeFeatureBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskPurposeFeatureBody
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskPurposeFeatureBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskPurposeFeatureBody
     */
    businessPurpose: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskPurposeFeatureBody
     */
    behavioralGoal: string;
}

/**
 * Check if a given object implements the UpdateTaskPurposeFeatureBody interface.
 */
export function instanceOfUpdateTaskPurposeFeatureBody(value: object): value is UpdateTaskPurposeFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('businessPurpose' in value) || value['businessPurpose'] === undefined) return false;
    if (!('behavioralGoal' in value) || value['behavioralGoal'] === undefined) return false;
    return true;
}

export function UpdateTaskPurposeFeatureBodyFromJSON(json: any): UpdateTaskPurposeFeatureBody {
    return UpdateTaskPurposeFeatureBodyFromJSONTyped(json, false);
}

export function UpdateTaskPurposeFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskPurposeFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'name': json['name'],
        'businessPurpose': json['businessPurpose'],
        'behavioralGoal': json['behavioralGoal'],
    };
}

export function UpdateTaskPurposeFeatureBodyToJSON(value?: UpdateTaskPurposeFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'name': value['name'],
        'businessPurpose': value['businessPurpose'],
        'behavioralGoal': value['behavioralGoal'],
    };
}

