/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordDefinition } from './RecordDefinition';
import {
    RecordDefinitionFromJSON,
    RecordDefinitionFromJSONTyped,
    RecordDefinitionToJSON,
} from './RecordDefinition';

/**
 * 
 * @export
 * @interface UpdateRecordOnTaskBody
 */
export interface UpdateRecordOnTaskBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordOnTaskBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRecordOnTaskBody
     */
    taskId: string;
    /**
     * 
     * @type {RecordDefinition}
     * @memberof UpdateRecordOnTaskBody
     */
    recordDefinition: RecordDefinition;
}

/**
 * Check if a given object implements the UpdateRecordOnTaskBody interface.
 */
export function instanceOfUpdateRecordOnTaskBody(value: object): value is UpdateRecordOnTaskBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('recordDefinition' in value) || value['recordDefinition'] === undefined) return false;
    return true;
}

export function UpdateRecordOnTaskBodyFromJSON(json: any): UpdateRecordOnTaskBody {
    return UpdateRecordOnTaskBodyFromJSONTyped(json, false);
}

export function UpdateRecordOnTaskBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRecordOnTaskBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'recordDefinition': RecordDefinitionFromJSON(json['recordDefinition']),
    };
}

export function UpdateRecordOnTaskBodyToJSON(value?: UpdateRecordOnTaskBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'recordDefinition': RecordDefinitionToJSON(value['recordDefinition']),
    };
}

