/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCase } from './TestCase';
import {
    TestCaseFromJSON,
    TestCaseFromJSONTyped,
    TestCaseToJSON,
} from './TestCase';

/**
 * 
 * @export
 * @interface UpdateTestCaseOnTaskBody
 */
export interface UpdateTestCaseOnTaskBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateTestCaseOnTaskBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTestCaseOnTaskBody
     */
    taskId: string;
    /**
     * 
     * @type {TestCase}
     * @memberof UpdateTestCaseOnTaskBody
     */
    testCase: TestCase;
}

/**
 * Check if a given object implements the UpdateTestCaseOnTaskBody interface.
 */
export function instanceOfUpdateTestCaseOnTaskBody(value: object): value is UpdateTestCaseOnTaskBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('testCase' in value) || value['testCase'] === undefined) return false;
    return true;
}

export function UpdateTestCaseOnTaskBodyFromJSON(json: any): UpdateTestCaseOnTaskBody {
    return UpdateTestCaseOnTaskBodyFromJSONTyped(json, false);
}

export function UpdateTestCaseOnTaskBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTestCaseOnTaskBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'taskId': json['taskId'],
        'testCase': TestCaseFromJSON(json['testCase']),
    };
}

export function UpdateTestCaseOnTaskBodyToJSON(value?: UpdateTestCaseOnTaskBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'taskId': value['taskId'],
        'testCase': TestCaseToJSON(value['testCase']),
    };
}

