/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDraftFeaturePurposeBody
 */
export interface UpdateDraftFeaturePurposeBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftFeaturePurposeBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftFeaturePurposeBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftFeaturePurposeBody
     */
    objective: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDraftFeaturePurposeBody
     */
    flowOverview: string;
}

/**
 * Check if a given object implements the UpdateDraftFeaturePurposeBody interface.
 */
export function instanceOfUpdateDraftFeaturePurposeBody(value: object): value is UpdateDraftFeaturePurposeBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('objective' in value) || value['objective'] === undefined) return false;
    if (!('flowOverview' in value) || value['flowOverview'] === undefined) return false;
    return true;
}

export function UpdateDraftFeaturePurposeBodyFromJSON(json: any): UpdateDraftFeaturePurposeBody {
    return UpdateDraftFeaturePurposeBodyFromJSONTyped(json, false);
}

export function UpdateDraftFeaturePurposeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDraftFeaturePurposeBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'name': json['name'],
        'objective': json['objective'],
        'flowOverview': json['flowOverview'],
    };
}

export function UpdateDraftFeaturePurposeBodyToJSON(value?: UpdateDraftFeaturePurposeBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'name': value['name'],
        'objective': value['objective'],
        'flowOverview': value['flowOverview'],
    };
}

