/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Position } from './Position';
import {
    PositionFromJSON,
    PositionFromJSONTyped,
    PositionToJSON,
} from './Position';

/**
 * 
 * @export
 * @interface WaypointUpdatedOnDraftFeatureBody
 */
export interface WaypointUpdatedOnDraftFeatureBody {
    /**
     * 
     * @type {string}
     * @memberof WaypointUpdatedOnDraftFeatureBody
     */
    featureId: string;
    /**
     * 
     * @type {string}
     * @memberof WaypointUpdatedOnDraftFeatureBody
     */
    fromTaskId: string;
    /**
     * 
     * @type {string}
     * @memberof WaypointUpdatedOnDraftFeatureBody
     */
    toTaskId: string;
    /**
     * 
     * @type {Array<Position>}
     * @memberof WaypointUpdatedOnDraftFeatureBody
     */
    positions: Array<Position>;
}

/**
 * Check if a given object implements the WaypointUpdatedOnDraftFeatureBody interface.
 */
export function instanceOfWaypointUpdatedOnDraftFeatureBody(value: object): value is WaypointUpdatedOnDraftFeatureBody {
    if (!('featureId' in value) || value['featureId'] === undefined) return false;
    if (!('fromTaskId' in value) || value['fromTaskId'] === undefined) return false;
    if (!('toTaskId' in value) || value['toTaskId'] === undefined) return false;
    if (!('positions' in value) || value['positions'] === undefined) return false;
    return true;
}

export function WaypointUpdatedOnDraftFeatureBodyFromJSON(json: any): WaypointUpdatedOnDraftFeatureBody {
    return WaypointUpdatedOnDraftFeatureBodyFromJSONTyped(json, false);
}

export function WaypointUpdatedOnDraftFeatureBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaypointUpdatedOnDraftFeatureBody {
    if (json == null) {
        return json;
    }
    return {
        
        'featureId': json['featureId'],
        'fromTaskId': json['fromTaskId'],
        'toTaskId': json['toTaskId'],
        'positions': ((json['positions'] as Array<any>).map(PositionFromJSON)),
    };
}

export function WaypointUpdatedOnDraftFeatureBodyToJSON(value?: WaypointUpdatedOnDraftFeatureBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'featureId': value['featureId'],
        'fromTaskId': value['fromTaskId'],
        'toTaskId': value['toTaskId'],
        'positions': ((value['positions'] as Array<any>).map(PositionToJSON)),
    };
}

