/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BpnContext,
  CreateContextBody,
} from '../models/index';
import {
    BpnContextFromJSON,
    BpnContextToJSON,
    CreateContextBodyFromJSON,
    CreateContextBodyToJSON,
} from '../models/index';

export interface CreateContextRequest {
    createContextBody: CreateContextBody;
}

/**
 * 
 */
export class ContainerApi extends runtime.BaseAPI {

    /**
     */
    async createContextRaw(requestParameters: CreateContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createContextBody'] == null) {
            throw new runtime.RequiredError(
                'createContextBody',
                'Required parameter "createContextBody" was null or undefined when calling createContext().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Context/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateContextBodyToJSON(requestParameters['createContextBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createContext(requestParameters: CreateContextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createContextRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllContextsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BpnContext>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/BpnEngine/v1/Context/All`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BpnContextFromJSON));
    }

    /**
     */
    async getAllContexts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BpnContext>> {
        const response = await this.getAllContextsRaw(initOverrides);
        return await response.value();
    }

}
