/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddPersonaBody,
  ComponentCosumedByPersonaBody,
  ComponentNoLongerConsumedByPersonaBody,
  Persona4,
  RemovePersonaBody,
  UpdatePersonaInformationBody,
} from '../models/index';
import {
    AddPersonaBodyFromJSON,
    AddPersonaBodyToJSON,
    ComponentCosumedByPersonaBodyFromJSON,
    ComponentCosumedByPersonaBodyToJSON,
    ComponentNoLongerConsumedByPersonaBodyFromJSON,
    ComponentNoLongerConsumedByPersonaBodyToJSON,
    Persona4FromJSON,
    Persona4ToJSON,
    RemovePersonaBodyFromJSON,
    RemovePersonaBodyToJSON,
    UpdatePersonaInformationBodyFromJSON,
    UpdatePersonaInformationBodyToJSON,
} from '../models/index';

export interface AddPersonaRequest {
    addPersonaBody: AddPersonaBody;
}

export interface ComponentNoLongerConsumedByPersonaRequest {
    componentNoLongerConsumedByPersonaBody: ComponentNoLongerConsumedByPersonaBody;
}

export interface PersonaConsumeComponentRequest {
    componentCosumedByPersonaBody: ComponentCosumedByPersonaBody;
}

export interface RemovePersonaRequest {
    removePersonaBody: RemovePersonaBody;
}

export interface UpdatePersonaRequest {
    updatePersonaInformationBody: UpdatePersonaInformationBody;
}

/**
 * 
 */
export class PersonaApi extends runtime.BaseAPI {

    /**
     */
    async addPersonaRaw(requestParameters: AddPersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['addPersonaBody'] == null) {
            throw new runtime.RequiredError(
                'addPersonaBody',
                'Required parameter "addPersonaBody" was null or undefined when calling addPersona().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddPersonaBodyToJSON(requestParameters['addPersonaBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async addPersona(requestParameters: AddPersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addPersonaRaw(requestParameters, initOverrides);
    }

    /**
     */
    async componentNoLongerConsumedByPersonaRaw(requestParameters: ComponentNoLongerConsumedByPersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['componentNoLongerConsumedByPersonaBody'] == null) {
            throw new runtime.RequiredError(
                'componentNoLongerConsumedByPersonaBody',
                'Required parameter "componentNoLongerConsumedByPersonaBody" was null or undefined when calling componentNoLongerConsumedByPersona().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/UnconsumeComponent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ComponentNoLongerConsumedByPersonaBodyToJSON(requestParameters['componentNoLongerConsumedByPersonaBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async componentNoLongerConsumedByPersona(requestParameters: ComponentNoLongerConsumedByPersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.componentNoLongerConsumedByPersonaRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllPersonasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Persona4>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/All`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(Persona4FromJSON));
    }

    /**
     */
    async getAllPersonas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Persona4>> {
        const response = await this.getAllPersonasRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async personaConsumeComponentRaw(requestParameters: PersonaConsumeComponentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['componentCosumedByPersonaBody'] == null) {
            throw new runtime.RequiredError(
                'componentCosumedByPersonaBody',
                'Required parameter "componentCosumedByPersonaBody" was null or undefined when calling personaConsumeComponent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/ConsumeComponent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ComponentCosumedByPersonaBodyToJSON(requestParameters['componentCosumedByPersonaBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async personaConsumeComponent(requestParameters: PersonaConsumeComponentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.personaConsumeComponentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async removePersonaRaw(requestParameters: RemovePersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['removePersonaBody'] == null) {
            throw new runtime.RequiredError(
                'removePersonaBody',
                'Required parameter "removePersonaBody" was null or undefined when calling removePersona().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/Remove`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: RemovePersonaBodyToJSON(requestParameters['removePersonaBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removePersona(requestParameters: RemovePersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removePersonaRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updatePersonaRaw(requestParameters: UpdatePersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['updatePersonaInformationBody'] == null) {
            throw new runtime.RequiredError(
                'updatePersonaInformationBody',
                'Required parameter "updatePersonaInformationBody" was null or undefined when calling updatePersona().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Persona/Update`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePersonaInformationBodyToJSON(requestParameters['updatePersonaInformationBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updatePersona(requestParameters: UpdatePersonaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePersonaRaw(requestParameters, initOverrides);
    }

}
