/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BpnSolution,
  CreateSolutionBody,
} from '../models/index';
import {
    BpnSolutionFromJSON,
    BpnSolutionToJSON,
    CreateSolutionBodyFromJSON,
    CreateSolutionBodyToJSON,
} from '../models/index';

export interface CreateSolutionRequest {
    createSolutionBody: CreateSolutionBody;
}

/**
 * 
 */
export class SolutionApi extends runtime.BaseAPI {

    /**
     */
    async createSolutionRaw(requestParameters: CreateSolutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createSolutionBody'] == null) {
            throw new runtime.RequiredError(
                'createSolutionBody',
                'Required parameter "createSolutionBody" was null or undefined when calling createSolution().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/Solution/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSolutionBodyToJSON(requestParameters['createSolutionBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSolution(requestParameters: CreateSolutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createSolutionRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllSolutionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BpnSolution>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/BpnEngine/v1/Solution/All`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BpnSolutionFromJSON));
    }

    /**
     */
    async getAllSolutions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BpnSolution>> {
        const response = await this.getAllSolutionsRaw(initOverrides);
        return await response.value();
    }

}
