/* tslint:disable */
/* eslint-disable */
/**
 * BpnEngine API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BpnSystem,
  CreateSystemBody,
} from '../models/index';
import {
    BpnSystemFromJSON,
    BpnSystemToJSON,
    CreateSystemBodyFromJSON,
    CreateSystemBodyToJSON,
} from '../models/index';

export interface CreateSystemRequest {
    createSystemBody: CreateSystemBody;
}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     */
    async createSystemRaw(requestParameters: CreateSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createSystemBody'] == null) {
            throw new runtime.RequiredError(
                'createSystemBody',
                'Required parameter "createSystemBody" was null or undefined when calling createSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/BpnEngine/v1/System/Add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSystemBodyToJSON(requestParameters['createSystemBody']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSystem(requestParameters: CreateSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createSystemRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllSystemsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BpnSystem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/BpnEngine/v1/System/All`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BpnSystemFromJSON));
    }

    /**
     */
    async getAllSystems(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BpnSystem>> {
        const response = await this.getAllSystemsRaw(initOverrides);
        return await response.value();
    }

}
