global using System.Reflection;

global using CanineSourceRepository.BusinessProcessNotation.BpnContext;
global using CanineSourceRepository.BusinessProcessNotation.BpnContext.BpnFeature;
global using CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnContext;
global using CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature;

global using static CanineSourceRepository.BusinessProcessNotation.BpnContext.BpnFeature.BpnFeatureDiagram;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnContext.CreateContextFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.AddDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.ReleaseFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.UpdateDraftFeaturePurposeFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.UpdateEnvironmentsOnFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.PositionUpdatedOnDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.RemoveTransitionFromDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.ResetDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.WaypointUpdatedOnDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.AddTaskToDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.AddTransitionToDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.FeaturesForBpnDraftFeature.RemoveTaskFromDraftFeatureFeature;
