global using System.Reflection;

global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.AddDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.CreateContextFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.ReleaseFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.UpdateDraftFeaturePurposeFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.UpdateEnvironmentsOnFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnContext.BpnFeature.BpnFeatureDiagram;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.PositionUpdatedOnDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.RemoveTransitionFromDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.ResetDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.WaypointUpdatedOnDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.AddTaskToDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.AddTransitionToDraftFeatureFeature;
global using static CanineSourceRepository.BusinessProcessNotation.BpnEventStore.Features.RemoveTaskFromDraftFeatureFeature;
